from typing import Literal

SubAgentRole = Literal[
    "MARKET_ANALYST",
    "RISK_ANALYST",
    "EQUITY_RESEARCH_ANALYST",
    "FUNDAMENTAL_ANALYST",
    "TECHNICAL_ANALYST",
    "TRADING_EXECUTOR",
    "EQUITY_SELECTION_ANALYST",
]

AgentRole = Literal[
    "CHIEF_INVESTMENT_OFFICER",
    "MARKET_ANALYST",
    "RISK_ANALYST",
    "EQUITY_RESEARCH_ANALYST",
    "FUNDAMENTAL_ANALYST",
    "TECHNICAL_ANALYST",
    "TRADING_EXECUTOR",
    "EQUITY_SELECTION_ANALYST",
]
